version: '3.8'

services:
 web:
   build: .
   ports:
     - "8000:8000"
   depends_on:
     db:
       condition: service_healthy
   environment:
     - POSTGRES_DB=gold_trading
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_HOST=db
   volumes:
     - .:/app

 db:
   image: postgres:13
   environment:
     - POSTGRES_DB=gold_trading
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 5s
     timeout: 5s
     retries: 5

volumes:
 postgres_data: